Casino/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :recaudacions
  resources :apertura_monedas
  resources :apertura_billetes
  resources :premio_manuals
  resources :musuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Casino/app/models/premio_manual.rb
class PremioManual < ApplicationRecord
end

Casino/app/controllers/premio_manuals_controller.rb
class PremioManualsController < ApplicationController
  before_action :set_premio_manual, only: [:show, :edit, :update, :destroy]

  # GET /premio_manuals
  # GET /premio_manuals.json
  def index
    @premio_manuals = PremioManual.all
  end

  # GET /premio_manuals/1
  # GET /premio_manuals/1.json
  def show
  end

  # GET /premio_manuals/new
  def new
    @premio_manual = PremioManual.new
  end

  # GET /premio_manuals/1/edit
  def edit
  end

  # POST /premio_manuals
  # POST /premio_manuals.json
  def create
    @premio_manual = PremioManual.new(premio_manual_params)

    respond_to do |format|
      if @premio_manual.save
        format.html { redirect_to @premio_manual, notice: 'Se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @premio_manual }
      else
        format.html { render :new }
        format.json { render json: @premio_manual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /premio_manuals/1
  # PATCH/PUT /premio_manuals/1.json
  def update
    respond_to do |format|
      if @premio_manual.update(premio_manual_params)
        format.html { redirect_to @premio_manual, notice: 'El premio de actualizo correctamente.' }
        format.json { render :show, status: :ok, location: @premio_manual }
      else
        format.html { render :edit }
        format.json { render json: @premio_manual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /premio_manuals/1
  # DELETE /premio_manuals/1.json
  def destroy
    @premio_manual.destroy
    respond_to do |format|
      format.html { redirect_to premio_manuals_url, notice: 'Se ha eliminado correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_premio_manual
      @premio_manual = PremioManual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def premio_manual_params
      params.require(:premio_manual).permit(:nformato, :fecha, :maquina, :valor, :coninicial, :confinal, :dni, :nomcliente, :apepaterno, :apematerno)
    end
end

Casino/app/helpers/premio_manuals_helper.rb
module PremioManualsHelper
end

Casino/app/views/premio_manuals/_form.html.erb
<%= form_with(model: premio_manual, local: true) do |form| %>
  <% if premio_manual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(premio_manual.errors.count, "error") %> prohibited this premio_manual from being saved:</h2>

      <ul>
      <% premio_manual.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   

  <form class="needs-validation" novalidate>
  <div class="form-row">
    <div class="col-md-4 mb-3"> 
      <%= form.label :'N° Formato' %>
      <%= form.text_field :nformato, id: :premio_manual_nformato %>                 
    </div>
    <div class="col-md-4 mb-3">      
      <%= form.label :'Fecha' %>
      <%= form.date_select :fecha, id: :premio_manual_fecha %>     
    </div>    

  <div class="row">
    <div class="offset-4 col-3">
      <%= form.submit%>
    </div>
  </div>

  </div>
  
  
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <%= form.label :'N° Maquina' %>
      <%= form.text_field :maquina,{ :class => "form-control", :placeholder => "Ingrese número de maquina"}%>
    </div>  
     <div class="col-md-4 mb-3">
      <%= form.label :Valor %>
      <%= form.text_field :valor,{ :class => "form-control", :placeholder => "Ingrese valor"}%>
    </div>   
  </div>

    <div class="form-row">
    <div class="col-md-4 mb-3">
       <%= form.label :'Contador Inicial' %>
       <%= form.text_field :coninicial,{ :class => "form-control", :placeholder => "Ingrese contador inicial"} %>
    </div>  
     <div class="col-md-4 mb-3">
      <%= form.label :'Contador Final' %>
       <%= form.text_field :confinal,{ :class => "form-control", :placeholder => "Ingrese contador final"} %>
    </div>   
  </div>

   <div class="form-row">
    <div class="col-md-4 mb-3">
      <%= form.label :DNI %>
      <%= form.number_field :dni, { :class => "form-control", :placeholder => "Ingrese DNI"}%>
    </div>  
    <div class="col-md-4 mb-3">
      <%= form.label :'Nombre Cliente' %>
      <%= form.text_field :nomcliente,{ :class => "form-control", :placeholder => "Nombre cliente"}%>
    </div>   
  </div>

  <div class="form-row">
    <div class="col-md-4 mb-3">
     <%= form.label :'Apellido Paterno' %>
    <%= form.text_field :apepaterno,{ :class => "form-control", :placeholder => "Ingrese apellido paterno"}%>
    </div>  
    <div class="col-md-4 mb-3">
     <%= form.label :'Apellido Materno' %>
    <%= form.text_field :apematerno,{ :class => "form-control", :placeholder => "Ingrese apellido materno"} %>
    </div> 

    <div class="form-row">  
       <div class="col-md-4 mb-1">
          
       </div>    
     </div> 

  


  </div>

    

  </form>
<% end %>

Casino/app/views/premio_manuals/edit.html.erb
<h1>Editing Premio Manual</h1>

<%= render 'form', premio_manual: @premio_manual %>

<%= link_to 'Listar', @premio_manual %> |
<%= link_to 'Atras', premio_manuals_path %>

Casino/app/views/premio_manuals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>PREMIO MANUALES</h1>
<div class="table-responsive-lg">
<table class="table w-auto">
  <thead class="thead-dark">
    <tr>
      <th>N° formato</th>
      <th>Fecha</th>
      <th>Maquina</th>
      <th>Valor</th>
      <th>Contador inicial</th>
      <th>Contador final</th>
      <th>DNI</th>
      <th>NomCliente</th>
      <th>ApePaterno</th>
      <th>ApeMaterno</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @premio_manuals.each do |premio_manual| %>
      <tr>
        <td><%= premio_manual.nformato %></td>
        <td><%= premio_manual.fecha %></td>
        <td><%= premio_manual.maquina %></td>
        <td><%= premio_manual.valor %></td>
        <td><%= premio_manual.coninicial %></td>
        <td><%= premio_manual.confinal %></td>
        <td><%= premio_manual.dni %></td>
        <td><%= premio_manual.nomcliente %></td>
        <td><%= premio_manual.apepaterno %></td>
        <td><%= premio_manual.apematerno %></td>
        <td class="btn btn-light"><%= link_to 'Mostrar', premio_manual %></td>
        <td class="btn btn-light"><%= link_to 'Editar', edit_premio_manual_path(premio_manual) %></td>
        <td class="btn btn-light"><%= link_to 'Eliminar', premio_manual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<button type="button" class="btn-outline-dark"><%= link_to 'Nuevo', new_premio_manual_path %></button>

Casino/app/views/premio_manuals/new.html.erb
<h5>Ingresar Premio Manual</h5>

<%= render 'form', premio_manual: @premio_manual %>
<%= link_to 'Atras', premio_manuals_path %>

Casino/app/views/premio_manuals/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>N° formato:</strong>
  <%= @premio_manual.nformato %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @premio_manual.fecha %>
</p>

<p>
  <strong>Maquina:</strong>
  <%= @premio_manual.maquina %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @premio_manual.valor %>
</p>

<p>
  <strong>Contador inicial:</strong>
  <%= @premio_manual.coninicial %>
</p>

<p>
  <strong>Contador final:</strong>
  <%= @premio_manual.confinal %>
</p>

<p>
  <strong>DNI:</strong>
  <%= @premio_manual.dni %>
</p>

<p>
  <strong>Nombre cliente:</strong>
  <%= @premio_manual.nomcliente %>
</p>

<p>
  <strong>Apellido paterno:</strong>
  <%= @premio_manual.apepaterno %>
</p>

<p>
  <strong>Apellido materno:</strong>
  <%= @premio_manual.apematerno %>
</p>

<%= link_to 'Editar', edit_premio_manual_path(@premio_manual) %> |
<%= link_to 'Atras', premio_manuals_path %>
</div>