Casino/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :recaudacions
  resources :apertura_monedas
  resources :apertura_billetes
  resources :premio_manuals
  resources :musuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Casino/app/models/musuario.rb
class Musuario < ApplicationRecord
end

Casino/app/controllers/musuarios_controller.rb
class MusuariosController < ApplicationController
  before_action :set_musuario, only: [:show, :edit, :update, :destroy]

  # GET /musuarios
  # GET /musuarios.json
  def index
    @musuarios = Musuario.all
  end

  # GET /musuarios/1
  # GET /musuarios/1.json
  def show
  end

  # GET /musuarios/new
  def new
    @musuario = Musuario.new
  end

  # GET /musuarios/1/edit
  def edit
  end

  # POST /musuarios
  # POST /musuarios.json
  def create
    @musuario = Musuario.new(musuario_params)

    respond_to do |format|
      if @musuario.save
        format.html { redirect_to @musuario, notice: 'Musuario was successfully created.' }
        format.json { render :show, status: :created, location: @musuario }
      else
        format.html { render :new }
        format.json { render json: @musuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musuarios/1
  # PATCH/PUT /musuarios/1.json
  def update
    respond_to do |format|
      if @musuario.update(musuario_params)
        format.html { redirect_to @musuario, notice: 'Musuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @musuario }
      else
        format.html { render :edit }
        format.json { render json: @musuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musuarios/1
  # DELETE /musuarios/1.json
  def destroy
    @musuario.destroy
    respond_to do |format|
      format.html { redirect_to musuarios_url, notice: 'Musuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musuario
      @musuario = Musuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def musuario_params
      params.require(:musuario).permit(:nombre, :apellidos, :usuario, :password, :sala, :tipo)
    end
end

Casino/app/helpers/musuarios_helper.rb
module MusuariosHelper
end

Casino/app/views/musuarios/_form.html.erb
<%= form_with(model: musuario, local: true) do |form| %>
  <% if musuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(musuario.errors.count, "error") %> prohibited this musuario from being saved:</h2>

      <ul>
      <% musuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :musuario_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos, id: :musuario_apellidos %>
  </div>

  <div class="field">
    <%= form.label :usuario %>
    <%= form.text_field :usuario, id: :musuario_usuario %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :musuario_password %>
  </div>

  <div class="field">
    <%= form.label :sala %>
    <%= form.text_field :sala, id: :musuario_sala %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :musuario_tipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Casino/app/views/musuarios/edit.html.erb
<h1>Editing Musuario</h1>

<%= render 'form', musuario: @musuario %>

<%= link_to 'Show', @musuario %> |
<%= link_to 'Back', musuarios_path %>

Casino/app/views/musuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Musuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Usuario</th>
      <th>Password</th>
      <th>Sala</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musuarios.each do |musuario| %>
      <tr>
        <td><%= musuario.nombre %></td>
        <td><%= musuario.apellidos %></td>
        <td><%= musuario.usuario %></td>
        <td><%= musuario.password %></td>
        <td><%= musuario.sala %></td>
        <td><%= musuario.tipo %></td>
        <td><%= link_to 'Show', musuario %></td>
        <td><%= link_to 'Edit', edit_musuario_path(musuario) %></td>
        <td><%= link_to 'Destroy', musuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Musuario', new_musuario_path %>

Casino/app/views/musuarios/new.html.erb
<h1>New Musuario</h1>

<%= render 'form', musuario: @musuario %>

<%= link_to 'Back', musuarios_path %>

Casino/app/views/musuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @musuario.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @musuario.apellidos %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @musuario.usuario %>
</p>

<p>
  <strong>Password:</strong>
  <%= @musuario.password %>
</p>

<p>
  <strong>Sala:</strong>
  <%= @musuario.sala %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @musuario.tipo %>
</p>

<%= link_to 'Edit', edit_musuario_path(@musuario) %> |
<%= link_to 'Back', musuarios_path %>