Casino/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :recaudacions
  resources :apertura_monedas
  resources :apertura_billetes
  resources :premio_manuals
  resources :musuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Casino/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Casino</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Archivo
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Salir</a>
          <a class="dropdown-item" href="#">Cerrar Sesión</a>         
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mov. Valores
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">         
          <%= link_to 'Premio Manual', premio_manuals_path %>          
          <%= link_to 'Aperturar Billete', apertura_billetes_path %>          
          <%= link_to 'Aperturar Moneda', apertura_monedas_path %>
          <%= link_to 'Recaudaciones', recaudacions_path %>
        </div>
      </li>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Incidencias
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#"> Generar OT</a>
          <a class="dropdown-item" href="#">Registrar Fciah Tecnica</a>         
        </div>
      </li>
     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Consultas
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Consulta 1</a>
          <a class="dropdown-item" href="#">Consulta 2</a>
          <a class="dropdown-item" href="#">Consulta 3</a>
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Reportes
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Reporte de total Venta</a>
          <a class="dropdown-item" href="#">Reportedel mes</a>
          <a class="dropdown-item" href="#">Reporte Mes</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div>
   <%= yield %>  
</div>
  </body>
</html>