Casino/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :recaudacions
  resources :apertura_monedas
  resources :apertura_billetes
  resources :premio_manuals
  resources :musuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Casino/app/models/recaudacion.rb
class Recaudacion < ApplicationRecord
end

Casino/app/controllers/recaudacions_controller.rb
class RecaudacionsController < ApplicationController
  before_action :set_recaudacion, only: [:show, :edit, :update, :destroy]

  # GET /recaudacions
  # GET /recaudacions.json
  def index
    @recaudacions = Recaudacion.all
  end

  # GET /recaudacions/1
  # GET /recaudacions/1.json
  def show
  end

  # GET /recaudacions/new
  def new
    @recaudacion = Recaudacion.new
  end

  # GET /recaudacions/1/edit
  def edit
  end

  # POST /recaudacions
  # POST /recaudacions.json
  def create
    @recaudacion = Recaudacion.new(recaudacion_params)

    respond_to do |format|
      if @recaudacion.save
        format.html { redirect_to @recaudacion, notice: 'Recaudacion was successfully created.' }
        format.json { render :show, status: :created, location: @recaudacion }
      else
        format.html { render :new }
        format.json { render json: @recaudacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recaudacions/1
  # PATCH/PUT /recaudacions/1.json
  def update
    respond_to do |format|
      if @recaudacion.update(recaudacion_params)
        format.html { redirect_to @recaudacion, notice: 'Recaudacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @recaudacion }
      else
        format.html { render :edit }
        format.json { render json: @recaudacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recaudacions/1
  # DELETE /recaudacions/1.json
  def destroy
    @recaudacion.destroy
    respond_to do |format|
      format.html { redirect_to recaudacions_url, notice: 'Recaudacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recaudacion
      @recaudacion = Recaudacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recaudacion_params
      params.require(:recaudacion).permit(:fechar, :horar, :nromaquinar, :rellenoini, :valorr, :monedafr, :rellenofin, :totalr, :totalfr)
    end
end

Casino/app/helpers/recaudacions_helper.rb
module RecaudacionsHelper
end

Casino/app/views/recaudacions/_form.html.erb
<%= form_with(model: recaudacion, local: true) do |form| %>
  <% if recaudacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recaudacion.errors.count, "error") %> prohibited this recaudacion from being saved:</h2>

      <ul>
      <% recaudacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fechar %>
    <%= form.date_select :fechar, id: :recaudacion_fechar %>
  </div>

  <div class="field">
    <%= form.label :horar %>
    <%= form.datetime_select :horar, id: :recaudacion_horar %>
  </div>

  <div class="field">
    <%= form.label :nromaquinar %>
    <%= form.number_field :nromaquinar, id: :recaudacion_nromaquinar %>
  </div>

  <div class="field">
    <%= form.label :rellenoini %>
    <%= form.text_field :rellenoini, id: :recaudacion_rellenoini %>
  </div>

  <div class="field">
    <%= form.label :valorr %>
    <%= form.text_field :valorr, id: :recaudacion_valorr %>
  </div>

  <div class="field">
    <%= form.label :monedafr %>
    <%= form.number_field :monedafr, id: :recaudacion_monedafr %>
  </div>

  <div class="field">
    <%= form.label :rellenofin %>
    <%= form.text_field :rellenofin, id: :recaudacion_rellenofin %>
  </div>

  <div class="field">
    <%= form.label :totalr %>
    <%= form.text_field :totalr, id: :recaudacion_totalr %>
  </div>

  <div class="field">
    <%= form.label :totalfr %>
    <%= form.number_field :totalfr, id: :recaudacion_totalfr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Casino/app/views/recaudacions/edit.html.erb
<h1>Editing Recaudacion</h1>

<%= render 'form', recaudacion: @recaudacion %>

<%= link_to 'Show', @recaudacion %> |
<%= link_to 'Back', recaudacions_path %>

Casino/app/views/recaudacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recaudacions</h1>

<table class="table w-auto">
  <thead class="thead-dark">
    <tr>
      <th>Fechar</th>
      <th>Horar</th>
      <th>Nromaquinar</th>
      <th>Rellenoini</th>
      <th>Valorr</th>
      <th>Monedafr</th>
      <th>Rellenofin</th>
      <th>Totalr</th>
      <th>Totalfr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recaudacions.each do |recaudacion| %>
      <tr>
        <td><%= recaudacion.fechar %></td>
        <td><%= recaudacion.horar %></td>
        <td><%= recaudacion.nromaquinar %></td>
        <td><%= recaudacion.rellenoini %></td>
        <td><%= recaudacion.valorr %></td>
        <td><%= recaudacion.monedafr %></td>
        <td><%= recaudacion.rellenofin %></td>
        <td><%= recaudacion.totalr %></td>
        <td><%= recaudacion.totalfr %></td>
        <td><%= link_to 'Show', recaudacion %></td>
        <td><%= link_to 'Edit', edit_recaudacion_path(recaudacion) %></td>
        <td><%= link_to 'Destroy', recaudacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recaudacion', new_recaudacion_path %>

Casino/app/views/recaudacions/new.html.erb
<h1>New Recaudacion</h1>

<%= render 'form', recaudacion: @recaudacion %>

<%= link_to 'Back', recaudacions_path %>

Casino/app/views/recaudacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fechar:</strong>
  <%= @recaudacion.fechar %>
</p>

<p>
  <strong>Horar:</strong>
  <%= @recaudacion.horar %>
</p>

<p>
  <strong>Nromaquinar:</strong>
  <%= @recaudacion.nromaquinar %>
</p>

<p>
  <strong>Rellenoini:</strong>
  <%= @recaudacion.rellenoini %>
</p>

<p>
  <strong>Valorr:</strong>
  <%= @recaudacion.valorr %>
</p>

<p>
  <strong>Monedafr:</strong>
  <%= @recaudacion.monedafr %>
</p>

<p>
  <strong>Rellenofin:</strong>
  <%= @recaudacion.rellenofin %>
</p>

<p>
  <strong>Totalr:</strong>
  <%= @recaudacion.totalr %>
</p>

<p>
  <strong>Totalfr:</strong>
  <%= @recaudacion.totalfr %>
</p>

<%= link_to 'Edit', edit_recaudacion_path(@recaudacion) %> |
<%= link_to 'Back', recaudacions_path %>